### ISSUE TITLE
Mod basic structure

### ISSUE THREAD

**Issue by Tujin** [nullVal/persist-nv#1]
Create initial layout of mod structure

**Comment by Tujin** [comment]
Ready for verification by @RobVice :

- [ ] Install mod into server (shouldn't matter if there are other mods loaded or not)
- [ ] Start server
- [ ] Should see in server console: "Persist-nv loaded."

**Comment by RobVice** [comment]
Messages do not appear in the console, and produces errors.

![17968316_10154900713740091_1858931701_o](https://cloud.githubusercontent.com/assets/18584052/25066526/0c000f0c-21f6-11e7-9906-beb6fc824563.png)

**Comment by RobVice** [comment]
Terry fixed via pull 7, now loads log file correctly.

![image](https://cloud.githubusercontent.com/assets/18584052/25066615/3d54c8ec-21f9-11e7-9171-7b71d8c76e1e.png)
